In [1]:
para = "This is my NLP session that is going on and im happy. is every one happy. also i learn in ineuron company"

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Nplite\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
import nltk  #Natural Langauge toolkit & Specy also library like scikitlearn

In [25]:
sentences = nltk.sent_tokenize(para)   # here we get a list of sentence

In [26]:
sentences

['This is my NLP session that is going on and im happy.',
 'is every one happy.',
 'also i learn in ineuron company']

In [27]:
nltk.word_tokenize(para)    # Tokanisation = We Convert senetences into word

['This',
 'is',
 'my',
 'NLP',
 'session',
 'that',
 'is',
 'going',
 'on',
 'and',
 'im',
 'happy',
 '.',
 'is',
 'every',
 'one',
 'happy',
 '.',
 'also',
 'i',
 'learn',
 'in',
 'ineuron',
 'company']

In [28]:
from nltk.stem import PorterStemmer

In [29]:
stemmer = PorterStemmer()

In [30]:
stemmer.stem('going')

'go'

In [31]:
stemmer.stem('finally')

'final'

In [32]:
stemmer.stem('history')

'histori'

In [33]:
stemmer.stem('manathon')

'manathon'

In [34]:
stemmer.stem('organisation')

'organis'

In [35]:
stemmer.stem('happy')

'happi'

Stemming = It is the process of convering word to their root form.

In [36]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Nplite\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [37]:
from nltk.stem import WordNetLemmatizer

In [38]:
limitiser = WordNetLemmatizer()

In [39]:
limitiser.lemmatize('history')

'history'

In [40]:
limitiser.lemmatize('historical')

'historical'

In [41]:
limitiser.lemmatize('going')

'going'

In [42]:
limitiser.lemmatize('finally')

'finally'

In [43]:
#limitiser will do camparision 

In [44]:
stemmer.stem(para)

'this is my nlp session that is going on and im happy. is every one happy. also i learn in ineuron compani'

In [45]:
limitiser.lemmatize(para)

'This is my NLP session that is going on and im happy. is every one happy. also i learn in ineuron company'

In [46]:
corpus = []
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words]
    print(words)
    corpus.append(" ".join(words))

['thi', 'is', 'my', 'nlp', 'session', 'that', 'is', 'go', 'on', 'and', 'im', 'happi', '.']
['is', 'everi', 'one', 'happi', '.']
['also', 'i', 'learn', 'in', 'ineuron', 'compani']


In [47]:
corpus

['thi is my nlp session that is go on and im happi .',
 'is everi one happi .',
 'also i learn in ineuron compani']

In [48]:
corpus = []
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [limitiser.lemmatize(word) for word in words]
    print(words)
    corpus.append(" ".join(words))

['This', 'is', 'my', 'NLP', 'session', 'that', 'is', 'going', 'on', 'and', 'im', 'happy', '.']
['is', 'every', 'one', 'happy', '.']
['also', 'i', 'learn', 'in', 'ineuron', 'company']


In [49]:
corpus

['This is my NLP session that is going on and im happy .',
 'is every one happy .',
 'also i learn in ineuron company']

In [50]:
par = "Promoted to management during the 1970s, Ratan achieved initial success by turning Group company National Radio and Electronics (NELCO) around, only to see it collapse during an economic slowdown.[14][15] In 1991, J. R. D. Tata stepped down as chairman of Tata Sons, naming him his successor. When he settled down into the new role, he faced stiff resistance from many companies heads, some of whom had spent decades in their respective companies and rose to become very powerful and influential due to the freedom to operate under JRD Tata. He began replacing them by setting a retirement age, and then made individual companies report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand. Innovation was given priority and younger talent was infused and given responsibilities.[16] Under his stewardship, overlapping operations in group companies were streamlined into a synergised whole,[17] with the salt-to-software group exiting unrelated businesses to take on globalisation."

In [51]:
par

'Promoted to management during the 1970s, Ratan achieved initial success by turning Group company National Radio and Electronics (NELCO) around, only to see it collapse during an economic slowdown.[14][15] In 1991, J. R. D. Tata stepped down as chairman of Tata Sons, naming him his successor. When he settled down into the new role, he faced stiff resistance from many companies heads, some of whom had spent decades in their respective companies and rose to become very powerful and influential due to the freedom to operate under JRD Tata. He began replacing them by setting a retirement age, and then made individual companies report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand. Innovation was given priority and younger talent was infused and given responsibilities.[16] Under his stewardship, overlapping operations in group companies were streamlined into a synergised whole,[17] with the salt-to-software group exiting

In [52]:
sentense = nltk.sent_tokenize(par)

In [53]:
nltk.word_tokenize(par)

['Promoted',
 'to',
 'management',
 'during',
 'the',
 '1970s',
 ',',
 'Ratan',
 'achieved',
 'initial',
 'success',
 'by',
 'turning',
 'Group',
 'company',
 'National',
 'Radio',
 'and',
 'Electronics',
 '(',
 'NELCO',
 ')',
 'around',
 ',',
 'only',
 'to',
 'see',
 'it',
 'collapse',
 'during',
 'an',
 'economic',
 'slowdown',
 '.',
 '[',
 '14',
 ']',
 '[',
 '15',
 ']',
 'In',
 '1991',
 ',',
 'J.',
 'R.',
 'D.',
 'Tata',
 'stepped',
 'down',
 'as',
 'chairman',
 'of',
 'Tata',
 'Sons',
 ',',
 'naming',
 'him',
 'his',
 'successor',
 '.',
 'When',
 'he',
 'settled',
 'down',
 'into',
 'the',
 'new',
 'role',
 ',',
 'he',
 'faced',
 'stiff',
 'resistance',
 'from',
 'many',
 'companies',
 'heads',
 ',',
 'some',
 'of',
 'whom',
 'had',
 'spent',
 'decades',
 'in',
 'their',
 'respective',
 'companies',
 'and',
 'rose',
 'to',
 'become',
 'very',
 'powerful',
 'and',
 'influential',
 'due',
 'to',
 'the',
 'freedom',
 'to',
 'operate',
 'under',
 'JRD',
 'Tata',
 '.',
 'He',
 'began',


In [54]:

corpus = []
for i in range(len(sentense)):
    words = nltk.word_tokenize(sentense[i])
    words = [limitiser.lemmatize(word) for word in words]
    print(words)
    corpus.append(" ".join(words))

['Promoted', 'to', 'management', 'during', 'the', '1970s', ',', 'Ratan', 'achieved', 'initial', 'success', 'by', 'turning', 'Group', 'company', 'National', 'Radio', 'and', 'Electronics', '(', 'NELCO', ')', 'around', ',', 'only', 'to', 'see', 'it', 'collapse', 'during', 'an', 'economic', 'slowdown', '.']
['[', '14', ']', '[', '15', ']', 'In', '1991', ',', 'J.', 'R.', 'D.', 'Tata', 'stepped', 'down', 'a', 'chairman', 'of', 'Tata', 'Sons', ',', 'naming', 'him', 'his', 'successor', '.']
['When', 'he', 'settled', 'down', 'into', 'the', 'new', 'role', ',', 'he', 'faced', 'stiff', 'resistance', 'from', 'many', 'company', 'head', ',', 'some', 'of', 'whom', 'had', 'spent', 'decade', 'in', 'their', 'respective', 'company', 'and', 'rose', 'to', 'become', 'very', 'powerful', 'and', 'influential', 'due', 'to', 'the', 'freedom', 'to', 'operate', 'under', 'JRD', 'Tata', '.']
['He', 'began', 'replacing', 'them', 'by', 'setting', 'a', 'retirement', 'age', ',', 'and', 'then', 'made', 'individual', 'comp

In [55]:
corpus

['Promoted to management during the 1970s , Ratan achieved initial success by turning Group company National Radio and Electronics ( NELCO ) around , only to see it collapse during an economic slowdown .',
 '[ 14 ] [ 15 ] In 1991 , J. R. D. Tata stepped down a chairman of Tata Sons , naming him his successor .',
 'When he settled down into the new role , he faced stiff resistance from many company head , some of whom had spent decade in their respective company and rose to become very powerful and influential due to the freedom to operate under JRD Tata .',
 'He began replacing them by setting a retirement age , and then made individual company report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand .',
 'Innovation wa given priority and younger talent wa infused and given responsibility .',
 '[ 16 ] Under his stewardship , overlapping operation in group company were streamlined into a synergised whole , [ 17 ] with t

In [56]:

corpus1 = []
for i in range(len(sentense)):
    words = nltk.word_tokenize(sentense[i])
    words = [stemmer.stem(word) for word in words]
    print(words)
    corpus1.append(" ".join(words))

['promot', 'to', 'manag', 'dure', 'the', '1970', ',', 'ratan', 'achiev', 'initi', 'success', 'by', 'turn', 'group', 'compani', 'nation', 'radio', 'and', 'electron', '(', 'nelco', ')', 'around', ',', 'onli', 'to', 'see', 'it', 'collaps', 'dure', 'an', 'econom', 'slowdown', '.']
['[', '14', ']', '[', '15', ']', 'in', '1991', ',', 'j.', 'r.', 'd.', 'tata', 'step', 'down', 'as', 'chairman', 'of', 'tata', 'son', ',', 'name', 'him', 'hi', 'successor', '.']
['when', 'he', 'settl', 'down', 'into', 'the', 'new', 'role', ',', 'he', 'face', 'stiff', 'resist', 'from', 'mani', 'compani', 'head', ',', 'some', 'of', 'whom', 'had', 'spent', 'decad', 'in', 'their', 'respect', 'compani', 'and', 'rose', 'to', 'becom', 'veri', 'power', 'and', 'influenti', 'due', 'to', 'the', 'freedom', 'to', 'oper', 'under', 'jrd', 'tata', '.']
['he', 'began', 'replac', 'them', 'by', 'set', 'a', 'retir', 'age', ',', 'and', 'then', 'made', 'individu', 'compani', 'report', 'oper', 'to', 'the', 'group', 'offic', 'and', 'made

In [57]:
corpus

['Promoted to management during the 1970s , Ratan achieved initial success by turning Group company National Radio and Electronics ( NELCO ) around , only to see it collapse during an economic slowdown .',
 '[ 14 ] [ 15 ] In 1991 , J. R. D. Tata stepped down a chairman of Tata Sons , naming him his successor .',
 'When he settled down into the new role , he faced stiff resistance from many company head , some of whom had spent decade in their respective company and rose to become very powerful and influential due to the freedom to operate under JRD Tata .',
 'He began replacing them by setting a retirement age , and then made individual company report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand .',
 'Innovation wa given priority and younger talent wa infused and given responsibility .',
 '[ 16 ] Under his stewardship , overlapping operation in group company were streamlined into a synergised whole , [ 17 ] with t

In [58]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Nplite\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [59]:
from nltk.corpus import stopwords # stopwords is english language
stop_words = stopwords.words("english")
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [60]:
top_words = ["not", "nor","no","none"]

In [61]:
for i in ['changes', 'change','changing','changer','changable']:
    print(limitiser.lemmatize(i))

change
change
changing
changer
changable


In [62]:
limitiser.lemmatize('sweets')

'sweet'

In [63]:
print('better: ', limitiser.lemmatize('better',pos='a'))

better:  good


In [64]:
limitiser.lemmatize('was')

'wa'

In [65]:
limitiser.lemmatize('has')

'ha'

In [66]:
corpus

['Promoted to management during the 1970s , Ratan achieved initial success by turning Group company National Radio and Electronics ( NELCO ) around , only to see it collapse during an economic slowdown .',
 '[ 14 ] [ 15 ] In 1991 , J. R. D. Tata stepped down a chairman of Tata Sons , naming him his successor .',
 'When he settled down into the new role , he faced stiff resistance from many company head , some of whom had spent decade in their respective company and rose to become very powerful and influential due to the freedom to operate under JRD Tata .',
 'He began replacing them by setting a retirement age , and then made individual company report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand .',
 'Innovation wa given priority and younger talent wa infused and given responsibility .',
 '[ 16 ] Under his stewardship , overlapping operation in group company were streamlined into a synergised whole , [ 17 ] with t

In [67]:

corpus = []
for i in range(len(sentense)):
    words = nltk.word_tokenize(sentense[i].lower())
    words = [stemmer.stem(word) for word in words if not word in stop_words ]
    print(words)
    corpus.append(" ".join(words))

['promot', 'manag', '1970', ',', 'ratan', 'achiev', 'initi', 'success', 'turn', 'group', 'compani', 'nation', 'radio', 'electron', '(', 'nelco', ')', 'around', ',', 'see', 'collaps', 'econom', 'slowdown', '.']
['[', '14', ']', '[', '15', ']', '1991', ',', 'j.', 'r.', 'd.', 'tata', 'step', 'chairman', 'tata', 'son', ',', 'name', 'successor', '.']
['settl', 'new', 'role', ',', 'face', 'stiff', 'resist', 'mani', 'compani', 'head', ',', 'spent', 'decad', 'respect', 'compani', 'rose', 'becom', 'power', 'influenti', 'due', 'freedom', 'oper', 'jrd', 'tata', '.']
['began', 'replac', 'set', 'retir', 'age', ',', 'made', 'individu', 'compani', 'report', 'oper', 'group', 'offic', 'made', 'contribut', 'profit', 'build', 'use', 'tata', 'group', 'brand', '.']
['innov', 'given', 'prioriti', 'younger', 'talent', 'infus', 'given', 'respons', '.']
['[', '16', ']', 'stewardship', ',', 'overlap', 'oper', 'group', 'compani', 'streamlin', 'synergis', 'whole', ',', '[', '17', ']', 'salt-to-softwar', 'group', 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


In [70]:
sentense

['Promoted to management during the 1970s, Ratan achieved initial success by turning Group company National Radio and Electronics (NELCO) around, only to see it collapse during an economic slowdown.',
 '[14][15] In 1991, J. R. D. Tata stepped down as chairman of Tata Sons, naming him his successor.',
 'When he settled down into the new role, he faced stiff resistance from many companies heads, some of whom had spent decades in their respective companies and rose to become very powerful and influential due to the freedom to operate under JRD Tata.',
 'He began replacing them by setting a retirement age, and then made individual companies report operationally to the group office and made each contribute some of their profit to build and use the Tata group brand.',
 'Innovation was given priority and younger talent was infused and given responsibilities.',
 '[16] Under his stewardship, overlapping operations in group companies were streamlined into a synergised whole,[17] with the salt-to

In [71]:
import re
corpus = []
for i in range(len(sentense)):
    text = re.sub('[^a-zA-Z0-9]'," ",sentense[i])
    text = text.lower()
    words = text.split()
    words = [stemmer.stem(word) for word in words if not word in stop_words ]
    print(words)
    corpus.append(" ".join(words))

['promot', 'manag', '1970', 'ratan', 'achiev', 'initi', 'success', 'turn', 'group', 'compani', 'nation', 'radio', 'electron', 'nelco', 'around', 'see', 'collaps', 'econom', 'slowdown']
['14', '15', '1991', 'j', 'r', 'tata', 'step', 'chairman', 'tata', 'son', 'name', 'successor']
['settl', 'new', 'role', 'face', 'stiff', 'resist', 'mani', 'compani', 'head', 'spent', 'decad', 'respect', 'compani', 'rose', 'becom', 'power', 'influenti', 'due', 'freedom', 'oper', 'jrd', 'tata']
['began', 'replac', 'set', 'retir', 'age', 'made', 'individu', 'compani', 'report', 'oper', 'group', 'offic', 'made', 'contribut', 'profit', 'build', 'use', 'tata', 'group', 'brand']
['innov', 'given', 'prioriti', 'younger', 'talent', 'infus', 'given', 'respons']
['16', 'stewardship', 'overlap', 'oper', 'group', 'compani', 'streamlin', 'synergis', 'whole', '17', 'salt', 'softwar', 'group', 'exit', 'unrel', 'busi', 'take', 'globalis']


In [72]:
corpus

['promot manag 1970 ratan achiev initi success turn group compani nation radio electron nelco around see collaps econom slowdown',
 '14 15 1991 j r tata step chairman tata son name successor',
 'settl new role face stiff resist mani compani head spent decad respect compani rose becom power influenti due freedom oper jrd tata',
 'began replac set retir age made individu compani report oper group offic made contribut profit build use tata group brand',
 'innov given prioriti younger talent infus given respons',
 '16 stewardship overlap oper group compani streamlin synergis whole 17 salt softwar group exit unrel busi take globalis']

In [73]:
import re
corpus = []
for i in range(len(sentense)):
    text = re.sub('[^a-zA-Z0-9]'," ",sentense[i])
    text = text.lower()
    words = text.split()
    words = [limitiser.lemmatize(word) for word in words if not word in stop_words ]
    print(words)
    corpus.append(" ".join(words))

['promoted', 'management', '1970s', 'ratan', 'achieved', 'initial', 'success', 'turning', 'group', 'company', 'national', 'radio', 'electronics', 'nelco', 'around', 'see', 'collapse', 'economic', 'slowdown']
['14', '15', '1991', 'j', 'r', 'tata', 'stepped', 'chairman', 'tata', 'son', 'naming', 'successor']
['settled', 'new', 'role', 'faced', 'stiff', 'resistance', 'many', 'company', 'head', 'spent', 'decade', 'respective', 'company', 'rose', 'become', 'powerful', 'influential', 'due', 'freedom', 'operate', 'jrd', 'tata']
['began', 'replacing', 'setting', 'retirement', 'age', 'made', 'individual', 'company', 'report', 'operationally', 'group', 'office', 'made', 'contribute', 'profit', 'build', 'use', 'tata', 'group', 'brand']
['innovation', 'given', 'priority', 'younger', 'talent', 'infused', 'given', 'responsibility']
['16', 'stewardship', 'overlapping', 'operation', 'group', 'company', 'streamlined', 'synergised', 'whole', '17', 'salt', 'software', 'group', 'exiting', 'unrelated', 'bu

In [74]:
corpus

['promoted management 1970s ratan achieved initial success turning group company national radio electronics nelco around see collapse economic slowdown',
 '14 15 1991 j r tata stepped chairman tata son naming successor',
 'settled new role faced stiff resistance many company head spent decade respective company rose become powerful influential due freedom operate jrd tata',
 'began replacing setting retirement age made individual company report operationally group office made contribute profit build use tata group brand',
 'innovation given priority younger talent infused given responsibility',
 '16 stewardship overlapping operation group company streamlined synergised whole 17 salt software group exiting unrelated business take globalisation']

In [75]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [78]:
cv.fit_transform(corpus)

<6x84 sparse matrix of type '<class 'numpy.int64'>'
	with 91 stored elements in Compressed Sparse Row format>

In [79]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 

In [82]:
# here we specific applied bag of words
cv.vocabulary_     #promote present at 50 index

{'promoted': 50,
 'management': 36,
 '1970s': 4,
 'ratan': 52,
 'achieved': 6,
 'initial': 32,
 'success': 73,
 'turning': 79,
 'group': 27,
 'company': 16,
 'national': 39,
 'radio': 51,
 'electronics': 21,
 'nelco': 40,
 'around': 8,
 'see': 62,
 'collapse': 15,
 'economic': 20,
 'slowdown': 65,
 '14': 0,
 '15': 1,
 '1991': 5,
 'tata': 78,
 'stepped': 69,
 'chairman': 14,
 'son': 67,
 'naming': 38,
 'successor': 74,
 'settled': 64,
 'new': 41,
 'role': 59,
 'faced': 23,
 'stiff': 71,
 'resistance': 55,
 'many': 37,
 'head': 28,
 'spent': 68,
 'decade': 18,
 'respective': 56,
 'rose': 60,
 'become': 9,
 'powerful': 47,
 'influential': 30,
 'due': 19,
 'freedom': 24,
 'operate': 43,
 'jrd': 34,
 'began': 10,
 'replacing': 53,
 'setting': 63,
 'retirement': 58,
 'age': 7,
 'made': 35,
 'individual': 29,
 'report': 54,
 'operationally': 45,
 'office': 42,
 'contribute': 17,
 'profit': 49,
 'build': 12,
 'use': 81,
 'brand': 11,
 'innovation': 33,
 'given': 25,
 'priority': 48,
 'younger'

In [83]:
cv = CountVectorizer(binary=True)

In [84]:
cv.fit_transform(corpus)

<6x84 sparse matrix of type '<class 'numpy.int64'>'
	with 91 stored elements in Compressed Sparse Row format>

In [85]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 

In [86]:
cv.vocabulary_

{'promoted': 50,
 'management': 36,
 '1970s': 4,
 'ratan': 52,
 'achieved': 6,
 'initial': 32,
 'success': 73,
 'turning': 79,
 'group': 27,
 'company': 16,
 'national': 39,
 'radio': 51,
 'electronics': 21,
 'nelco': 40,
 'around': 8,
 'see': 62,
 'collapse': 15,
 'economic': 20,
 'slowdown': 65,
 '14': 0,
 '15': 1,
 '1991': 5,
 'tata': 78,
 'stepped': 69,
 'chairman': 14,
 'son': 67,
 'naming': 38,
 'successor': 74,
 'settled': 64,
 'new': 41,
 'role': 59,
 'faced': 23,
 'stiff': 71,
 'resistance': 55,
 'many': 37,
 'head': 28,
 'spent': 68,
 'decade': 18,
 'respective': 56,
 'rose': 60,
 'become': 9,
 'powerful': 47,
 'influential': 30,
 'due': 19,
 'freedom': 24,
 'operate': 43,
 'jrd': 34,
 'began': 10,
 'replacing': 53,
 'setting': 63,
 'retirement': 58,
 'age': 7,
 'made': 35,
 'individual': 29,
 'report': 54,
 'operationally': 45,
 'office': 42,
 'contribute': 17,
 'profit': 49,
 'build': 12,
 'use': 81,
 'brand': 11,
 'innovation': 33,
 'given': 25,
 'priority': 48,
 'younger'

In [87]:
cv = CountVectorizer(binary=True, ngram_range=(1,2))

In [89]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [90]:
cv.vocabulary_

{'promoted': 107,
 'management': 79,
 '1970s': 8,
 'ratan': 111,
 'achieved': 12,
 'initial': 70,
 'success': 151,
 'turning': 164,
 'group': 57,
 'company': 31,
 'national': 85,
 'radio': 109,
 'electronics': 45,
 'nelco': 87,
 'around': 16,
 'see': 130,
 'collapse': 29,
 'economic': 43,
 'slowdown': 136,
 'promoted management': 108,
 'management 1970s': 80,
 '1970s ratan': 9,
 'ratan achieved': 112,
 'achieved initial': 13,
 'initial success': 71,
 'success turning': 152,
 'turning group': 165,
 'group company': 59,
 'company national': 33,
 'national radio': 86,
 'radio electronics': 110,
 'electronics nelco': 46,
 'nelco around': 88,
 'around see': 17,
 'see collapse': 131,
 'collapse economic': 30,
 'economic slowdown': 44,
 '14': 0,
 '15': 2,
 '1991': 10,
 'tata': 160,
 'stepped': 143,
 'chairman': 27,
 'son': 139,
 'naming': 83,
 'successor': 153,
 '14 15': 1,
 '15 1991': 3,
 '1991 tata': 11,
 'tata stepped': 163,
 'stepped chairman': 144,
 'chairman tata': 28,
 'tata son': 162,

In [91]:
cv = CountVectorizer(binary=True, ngram_range=(2,2))

In [93]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [94]:
cv.vocabulary_

{'promoted management': 57,
 'management 1970s': 43,
 '1970s ratan': 4,
 'ratan achieved': 59,
 'achieved initial': 6,
 'initial success': 38,
 'success turning': 78,
 'turning group': 85,
 'group company': 31,
 'company national': 16,
 'national radio': 46,
 'radio electronics': 58,
 'electronics nelco': 24,
 'nelco around': 47,
 'around see': 8,
 'see collapse': 68,
 'collapse economic': 14,
 'economic slowdown': 23,
 '14 15': 0,
 '15 1991': 1,
 '1991 tata': 5,
 'tata stepped': 84,
 'stepped chairman': 74,
 'chairman tata': 13,
 'tata son': 83,
 'son naming': 72,
 'naming successor': 45,
 'settled new': 70,
 'new role': 48,
 'role faced': 65,
 'faced stiff': 26,
 'stiff resistance': 76,
 'resistance many': 62,
 'many company': 44,
 'company head': 15,
 'head spent': 34,
 'spent decade': 73,
 'decade respective': 21,
 'respective company': 63,
 'company rose': 18,
 'rose become': 66,
 'become powerful': 9,
 'powerful influential': 54,
 'influential due': 36,
 'due freedom': 22,
 'free

In [95]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [96]:
tf_idf = TfidfVectorizer()

In [97]:
tf_idf.fit_transform(corpus)

<6x84 sparse matrix of type '<class 'numpy.float64'>'
	with 91 stored elements in Compressed Sparse Row format>

In [98]:
tf_idf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23681493,
        0.        , 0.23681493, 0.        , 0.23681493, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.23681493, 0.14049262, 0.        , 0.        , 0.        ,
        0.23681493, 0.23681493, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.16394991, 0.        , 0.        ,
        0.        , 0.        , 0.23681493, 0.        , 0.        ,
        0.        , 0.23681493, 0.        , 0.        , 0.23681493,
        0.23681493, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.23681493, 0.23681493, 0.23681493, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.23681493, 0.        , 0.        ,
        0.23681493, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.23

In [99]:
tf_idf = TfidfVectorizer(binary=True, ngram_range=(1,20))

In [100]:
tf_idf.fit_transform(corpus)

<6x898 sparse matrix of type '<class 'numpy.float64'>'
	with 906 stored elements in Compressed Sparse Row format>

In [101]:
tf_idf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.13674365, 0.13674365, 0.13674365, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.16903085, 0.16903085,
        0.16903085],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [102]:
tf_idf.vocabulary_

{'promoted': 544,
 'management': 400,
 '1970s': 46,
 'ratan': 571,
 'achieved': 71,
 'initial': 354,
 'success': 820,
 'turning': 863,
 'group': 279,
 'company': 152,
 'national': 436,
 'radio': 563,
 'electronics': 235,
 'nelco': 445,
 'around': 102,
 'see': 701,
 'collapse': 149,
 'economic': 233,
 'slowdown': 743,
 'promoted management': 545,
 'management 1970s': 401,
 '1970s ratan': 47,
 'ratan achieved': 572,
 'achieved initial': 72,
 'initial success': 355,
 'success turning': 821,
 'turning group': 864,
 'group company': 281,
 'company national': 167,
 'national radio': 437,
 'radio electronics': 564,
 'electronics nelco': 236,
 'nelco around': 446,
 'around see': 103,
 'see collapse': 702,
 'collapse economic': 150,
 'economic slowdown': 234,
 'promoted management 1970s': 546,
 'management 1970s ratan': 402,
 '1970s ratan achieved': 48,
 'ratan achieved initial': 573,
 'achieved initial success': 73,
 'initial success turning': 356,
 'success turning group': 822,
 'turning grou

In [112]:
#new test data for prediction
data = ['I want to have food with ratan tata and promoted management team']

In [113]:
cv.transform(data)

<1x90 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [114]:
cv.transform(data).toarray() # here outof vocabulory problem

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=int64)

In [117]:
import pickle
pickle.dump(open('tfidf.pkl','wb'))

TypeError: dump() missing required argument 'file' (pos 2)

### Project 

In [131]:
import pandas as pd

In [132]:
df = pd.read_csv('SMSSpamCollection', sep= '\t',header=None)

In [133]:
df.head()

0                                                  1
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [134]:
df.columns = ['label','message']

In [135]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [136]:
#Data Cleaning and text preprocessing

In [141]:
import re
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [148]:
stop_word_list = ['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ma'
 ]
                  

In [149]:
stop_word_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [150]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [152]:
corpus = []
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z0-9]'," ", df['message'][i] )
    review =review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stop_word_list]
    review = " ".join(review)
    corpus.append(review)

In [153]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week no word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother not like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent won 1 we

In [159]:
#after cleaning we applly bag of word or tf idf
#first we do train test splite for avoiding data leakages problem

In [201]:
# independent features and dependent features
x = corpus
y = pd.get_dummies(df['label'],drop_first=True)

In [202]:
x

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week no word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother not like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent won 1 we

In [203]:
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [204]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [205]:
x_train

['certainli put thing perspect someth like happen',
 'hope great day',
 'hard live 121 chat 60p min choos girl connect live call 09094646899 cheap chat uk biggest live servic vu bcm1896wc1n3xx',
 'hiya probabl come home weekend next',
 'liter bed like lt gt hour',
 'tri reach without success',
 'wanna watch movi',
 'feel nauseou piss didn eat sweet week caus today plan pig diet week not hungri',
 'wait know wesley town bet hella drug',
 'came hostel',
 'sm ac blind date 4u rodds1 21 aberdeen unit kingdom check http img sm ac w icmb3cktz8r7 4 no blind date send hide',
 'u welcom caught u use broken english',
 'also rememb get dobbi bowl car',
 'wat da decis',
 'pl pl send mail know rel come deliv know cost risk benefit anyth els thank',
 'gonna worri noth won give money no use',
 'anyway mani good even u',
 'fine got enough bud last night least',
 'want kfc tuesday buy 2 meal 2 no gravi 2 mark 2',
 'photoshop make comput shut',
 'ye think offic lap room think that last day didnt shut',


In [206]:
x_test

['yun buy school got offer 2000 plu',
 'yar lor wait 4 mum 2 finish sch lunch lor whole morn stay home clean room room quit clean hee',
 'use foreign stamp whatev send',
 'wait 4 insid da car park',
 'yo watch movi netflix',
 'ye princess toledo',
 'realli good dhanush rock',
 'repli win 100 weekli 2006 fifa world cup held send stop 87239 end servic',
 'notic like look shit mirror your turn right freak',
 'sm auction brand new nokia 7250 4 auction today auction free 2 join take part txt nokia 86021 hg suite342 2land row w1j6hl',
 'dai download exe file run exe instal',
 'aight time want come',
 'tell who pl',
 'not heard u4 call night knicker make beg like u last time 01223585236 xx luv nikiyu4 net',
 'reach home 5 min',
 'engalnd telli decid won let watch mia elliot kiss damn',
 'effect irrit ignor',
 'dun thk quit yet hmmm go jazz yogasana oso go meet em lesson den',
 'make happi',
 'haf u found feel stupid da v cam work',
 'dun wan watch infern affair',
 'thesmszon com let send free

In [207]:
y_train

spam
4159     0
4655     0
3153     1
4530     0
4044     0
...    ...
2210     0
825      0
1122     1
483      0
3706     0

[4457 rows x 1 columns]

In [208]:
y_test

spam
1160     0
571      0
2698     0
3116     0
2758     0
...    ...
1906     0
4715     0
3237     0
3984     0
2555     0

[1115 rows x 1 columns]

In [209]:
#Here we apply Bag Of Words

In [210]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [211]:
 # Here dataset is imbalance 


In [212]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))# max_feature used for selecting top 2500 max words 
x_train = cv.fit_transform(x_train).toarray()
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [213]:
x_test = cv.transform(x_test).toarray()
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [214]:
x_train.shape # Here we balance the dataset

(4457, 2500)

In [215]:
y_train.shape

(4457, 1)

In [216]:
cv.vocabulary_  # these become a index between a 2500

{'put': 1737,
 'thing': 2157,
 'someth': 1994,
 'like': 1237,
 'happen': 987,
 'someth like': 1995,
 'hope': 1050,
 'great': 944,
 'day': 579,
 'hope great': 1055,
 'great day': 945,
 'hard': 994,
 'live': 1252,
 'chat': 431,
 '60p': 107,
 'min': 1372,
 'choos': 444,
 'girl': 879,
 'connect': 504,
 'call': 359,
 'cheap': 433,
 'uk': 2273,
 'biggest': 294,
 'servic': 1914,
 '60p min': 108,
 'hiya': 1028,
 'probabl': 1721,
 'come': 481,
 'home': 1045,
 'weekend': 2399,
 'next': 1487,
 'come home': 484,
 'bed': 279,
 'lt': 1297,
 'gt': 952,
 'hour': 1064,
 'like lt': 1241,
 'lt gt': 1299,
 'tri': 2233,
 'reach': 1761,
 'without': 2434,
 'success': 2079,
 'wanna': 2365,
 'watch': 2383,
 'movi': 1432,
 'feel': 762,
 'piss': 1647,
 'didn': 615,
 'eat': 677,
 'sweet': 2102,
 'week': 2396,
 'caus': 414,
 'today': 2197,
 'plan': 1659,
 'pig': 1644,
 'diet': 619,
 'not': 1525,
 'hungri': 1074,
 'today plan': 2201,
 'wait': 2355,
 'know': 1174,
 'town': 2225,
 'hella': 1010,
 'drug': 662,
 'came'

In [217]:
#above 2500 there are some of the words we have to ignore them


In [218]:
from sklearn.ensemble import RandomForestClassifier
Classifier = RandomForestClassifier().fit(x_train,y_train)

<ipython-input-218-1d0e2c1c1c28>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Classifier = RandomForestClassifier().fit(x_train,y_train)


In [219]:
y_predict = Classifier.predict(x_test)

In [222]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [223]:
accuracy_score(y_test,y_predict)

0.9820627802690582

In [224]:
confusion_matrix(y_test, y_predict)

array([[958,   1],
       [ 19, 137]], dtype=int64)

In [225]:
#here it is good we are reducing false positive by hyperparameter tunning

In [226]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       959
           1       0.99      0.88      0.93       156

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [229]:
from nltk.stem import WordNetLemmatizer
lem= WordNetLemmatizer()

In [230]:
corpus = []
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z0-9]'," ", df['message'][i] )
    review =review.lower()
    review = review.split()
    review = [lem.lemmatize(word) for word in review if word not in stop_word_list]
    review = " ".join(review)
    corpus.append(review)

In [231]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling 3 week no word back like fun still tb ok xxx std chgs send 1 50 rcv',
 'even brother not like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune',
 'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6days 16 tsandcs appl

In [232]:
# independent features and dependent features
x = corpus
y = pd.get_dummies(df['label'],drop_first=True)

In [233]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [234]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [235]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer(binary=True, ngram_range=(1,2))

In [236]:
tf_idf.fit_transform(x_train).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [238]:
tf_idf.transform(x_test).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [242]:
tf_idf.vocabulary_

{'hey': 13698,
 'gorgeous': 12454,
 'man': 17806,
 'work': 32489,
 'mobile': 18758,
 'number': 20733,
 'good': 12327,
 'one': 21203,
 'babe': 3498,
 'squishy': 26952,
 'mwahs': 19430,
 'hey gorgeous': 13728,
 'gorgeous man': 12457,
 'man work': 17832,
 'work mobile': 32524,
 'mobile number': 18794,
 'number good': 20752,
 'good one': 12390,
 'one babe': 21208,
 'babe squishy': 3537,
 'squishy mwahs': 26953,
 'morning': 19007,
 'dear': 7862,
 'shijutta': 25640,
 'great': 12691,
 'amp': 2567,
 'successful': 27570,
 'day': 7710,
 'good morning': 12380,
 'morning dear': 19015,
 'dear shijutta': 7899,
 'shijutta great': 25641,
 'great amp': 12693,
 'amp successful': 2606,
 'successful day': 27571,
 'idk': 14579,
 'keep': 15503,
 'saying': 24895,
 'not': 20407,
 'since': 25947,
 'moved': 19087,
 'butting': 4945,
 'head': 13472,
 'freedom': 10968,
 'responsibility': 24153,
 'tired': 29260,
 'much': 19248,
 'shit': 25663,
 'deal': 7848,
 'barely': 3774,
 'keeping': 15541,
 'together': 29417,
 

In [246]:
from sklearn.ensemble import RandomForestClassifier
Classifier = RandomForestClassifier().fit(x_train,y_train)

ValueError: could not convert string to float: 'hey gorgeous man work mobile number good one babe squishy mwahs'