In [1]:
import numpy as np

In [2]:
l = ['sudh',1,2,3,4,5,6]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['sudh', '1', '2', '3', '4', '5', '6'], dtype='<U11')

In [5]:
type(np.array(l))  #ndarray = n diamentional array

numpy.ndarray

In [6]:
np.array([3,4,5,6,7,3.0])

array([3., 4., 5., 6., 7., 3.])

In [7]:
a1 = np.array([3,4,5,6,7,3.0])

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
a = np.array([[1,2],[3,4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
a[1]

array([3, 4])

In [12]:
a[1][1]

4

In [13]:
a1

array([3., 4., 5., 6., 7., 3.])

In [14]:
a1[1]

4.0

In [15]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [16]:
np.array([1,2,3,4],ndmin = 0)

array([1, 2, 3, 4])

In [17]:
np.array([1,2,3,4],ndmin = 1)

array([1, 2, 3, 4])

In [18]:
np.array([1,2,3,4],ndmin = 2)

array([[1, 2, 3, 4]])

In [19]:
np.array([1,2,3,4],ndmin = 3)  # every diamention add one square bracket

array([[[1, 2, 3, 4]]])

In [20]:
np.array([1,2,3,4],ndmin = 4)

array([[[[1, 2, 3, 4]]]])

In [23]:
a2 =np.array([1,2,3,4],ndmin = 7)

In [24]:
a2

array([[[[[[[1, 2, 3, 4]]]]]]])

In [25]:
#fetch 1 from a2

In [26]:
a2[0]

array([[[[[[1, 2, 3, 4]]]]]])

In [25]:
a2[0][0][0][0]

1

In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [28]:
np.asarray([1,2,3,4,5])     # these are near about same

array([1, 2, 3, 4, 5])

In [29]:
np.asanyarray([1,2,3,4,5])  # array can be any diamention

array([1, 2, 3, 4, 5])

In [30]:
np.mat([1,2,3,4,5]) # matrix can default at any point of a time it will give 2 diamentional

matrix([[1, 2, 3, 4, 5]])

In [31]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [32]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [33]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [34]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [35]:
np.fromfunction(lambda i ,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j : i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [37]:
np.fromfunction(lambda i,j : i*j ,(4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [38]:
np.mat(np.fromfunction(lambda i,j : i*j ,(4,4), dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [39]:
np.mat(np.fromfunction(lambda i,j,z: i*j*z ,(3,3,3), dtype = int))   # it is not able to give result

ValueError: shape too large to be a matrix.

In [40]:
np.fromfunction(lambda i,j,z : i*j*z ,(3,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [41]:
np.fromfunction(lambda i,j,z : i*j*z ,(3,3,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [42]:
np.fromfunction(lambda i,j,z : i*j*z ,(2,3,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]]])

In [43]:
np.fromfunction(lambda i,j,z : i*j*z ,(4,3,3), dtype = int)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12]]])

In [44]:
#(4,3,3) these are three diamentional array X,Y,Z

In [45]:
np.fromfunction(lambda i,j,z,p : i*j*z*p ,(4,3,2,2), dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [46]:
# these are the 4 diamentional array (4,3,2,2)
# also check the number of squre bracket which will also shows the diamention of matrixes
# we can create any number of diamention its not limit

In [47]:
a = np.fromfunction(lambda i,j,z, : i*j*z ,(4,3,2), dtype = int)

In [48]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [49]:
a.ndim

3

In [50]:
a.size               # it will show how many elements inside a perticular array

24

In [51]:
a.shape

(4, 3, 2)

In [52]:
a.dtype

dtype('int32')

In [53]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [54]:
#dataframe is a 2d matrix or 2d arrays

In [55]:
import pandas as pd

In [56]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a = np.fromfunction(lambda i,j : i*j ,(4,3), dtype = int)

In [57]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [58]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [59]:
a = np.fromfunction(lambda i,j : i*j ,(400,100), dtype = int)

In [60]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [61]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [62]:
np.random.rand(100,4)

array([[6.91360501e-01, 3.29746834e-02, 7.44516195e-01, 8.40212105e-01],
       [3.86505623e-01, 2.29823807e-01, 4.74481260e-01, 4.15510414e-01],
       [9.58468658e-01, 4.44163799e-01, 5.50666517e-01, 5.12904944e-01],
       [3.06389781e-02, 3.14218227e-01, 3.79938570e-01, 5.07748224e-01],
       [4.63871752e-01, 4.11215748e-01, 7.07285538e-01, 9.57127840e-01],
       [3.46100634e-01, 9.86635819e-02, 5.85832973e-01, 3.41716200e-02],
       [5.77496542e-01, 2.24354838e-01, 8.45949835e-02, 6.86821291e-01],
       [8.69231518e-01, 6.08372149e-01, 2.81213008e-03, 2.58956242e-01],
       [8.25266969e-01, 4.16162866e-01, 2.49562361e-01, 6.40343246e-02],
       [6.11409902e-01, 7.53997219e-01, 8.44789311e-01, 5.42835687e-01],
       [6.86891335e-02, 6.13957418e-01, 1.04431139e-01, 5.22048832e-01],
       [3.63899268e-01, 7.76877600e-01, 3.65901124e-01, 3.59473935e-02],
       [9.68780566e-01, 2.88494304e-01, 6.63453349e-01, 2.40124638e-01],
       [7.91313487e-01, 7.63032942e-01, 3.59327824e

In [29]:
np.random.randint(4,50)   #run continious and check result

10

In [28]:
np.random.randn(4,5)

array([[-1.55084032,  1.44811833, -0.03435718,  0.31853857,  0.69440715],
       [ 0.09884763, -0.55764929, -1.15135867, -0.53405645,  0.08020259],
       [-0.15510954, -1.54793892,  0.31288288,  0.60731958,  1.25199229],
       [ 1.10219743,  0.12830432, -0.28173373, -0.19934432,  0.82905129]])

In [65]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.161593  1.511457 -1.165727 -0.348423  1.277117
1 -0.601196 -1.264089 -0.749714  0.932230  0.777710
2 -0.753403 -1.230151 -0.041911  0.564415  0.313610
3 -0.746337  0.650347 -0.779214  0.765663 -0.846348

In [66]:
#convert 3d into a 2d of a data

In [67]:
a = np.fromfunction(lambda i,j,z, : i*j*z ,(4,3,2), dtype = int)

In [68]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [69]:
a.reshape(12,2)    # set as per multiplication is possible (4,3,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [70]:
a.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [71]:
a.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [72]:
a.reshape(3,8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [73]:
a.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [74]:
pd.DataFrame(a.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [75]:
a.reshape(4,2,1,3)   #it will convert into 4 dimention

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [76]:
a.reshape(4,2,1,1,3)    #3d into 5d

array([[[[[0, 0, 0]]],


        [[[0, 0, 0]]]],



       [[[[0, 0, 0]]],


        [[[1, 0, 2]]]],



       [[[[0, 0, 0]]],


        [[[2, 0, 4]]]],



       [[[[0, 0, 0]]],


        [[[3, 0, 6]]]]])

In [77]:
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [78]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [79]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [80]:
a.reshape(2,-154236)  # any negative numbers and it is consider as a -1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [81]:
a.reshape(2,4,-234)    #2*4=8 and required 3 for 24 so it will consider negative number as a 3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [82]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [83]:
list(range(4,10,2))

[4, 6, 8]

In [84]:
list(range(4,10,.2)) # range function always consider a int values

TypeError: 'float' object cannot be interpreted as an integer

In [85]:
 np.arange(4,10,.2)  # every time it will jump of 0.2 steps
#by using numpy it will possible

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [86]:
np.arange(4,10.5,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [87]:
a1 = np.arange(4,10.5,0.2)

In [88]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [89]:
a1[1:4]   # slicing operation

array([4.2, 4.4, 4.6])

In [90]:
arr = np.random.rand(4,5)

In [91]:
arr

array([[0.57116946, 0.15061025, 0.954462  , 0.14785237, 0.33116738],
       [0.88916998, 0.38514255, 0.25333302, 0.34793789, 0.61222092],
       [0.11898795, 0.66329201, 0.28989945, 0.29991286, 0.63077402],
       [0.18603696, 0.8879323 , 0.3041137 , 0.25413923, 0.94451365]])

In [92]:
# try to extract all the data which is greater than 0.5

In [93]:
arr > 0.5 # same like pandas

array([[ True, False,  True, False, False],
       [ True, False, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True, False, False,  True]])

In [94]:
arr[arr>.5]

array([0.57116946, 0.954462  , 0.88916998, 0.61222092, 0.66329201,
       0.63077402, 0.8879323 , 0.94451365])

In [95]:
arr

array([[0.57116946, 0.15061025, 0.954462  , 0.14785237, 0.33116738],
       [0.88916998, 0.38514255, 0.25333302, 0.34793789, 0.61222092],
       [0.11898795, 0.66329201, 0.28989945, 0.29991286, 0.63077402],
       [0.18603696, 0.8879323 , 0.3041137 , 0.25413923, 0.94451365]])

In [96]:
# try to give specific elements

In [97]:
arr[[1,2],[2]]

array([0.25333302, 0.28989945])

In [98]:
# we can used iloc and loc by coverting this data into dataframe and then apply it

In [99]:
arr = np.random.rand(8,5)

In [100]:
arr

array([[0.79958208, 0.87757302, 0.51841684, 0.21308259, 0.94518547],
       [0.23796595, 0.70774173, 0.05502202, 0.81255234, 0.4226759 ],
       [0.06959043, 0.08272529, 0.76775645, 0.58234051, 0.87154278],
       [0.63276813, 0.22742075, 0.11446601, 0.15516758, 0.6932206 ],
       [0.45111617, 0.12324064, 0.35490942, 0.10205173, 0.65045803],
       [0.82953749, 0.09729264, 0.67008506, 0.71034379, 0.08787481],
       [0.25839239, 0.94053517, 0.05341007, 0.40768647, 0.18495674],
       [0.5243085 , 0.79357529, 0.32319951, 0.71559149, 0.03849401]])

In [101]:
arr[1:8,0:3] # this is a another method for fetching specific dataset

array([[0.23796595, 0.70774173, 0.05502202],
       [0.06959043, 0.08272529, 0.76775645],
       [0.63276813, 0.22742075, 0.11446601],
       [0.45111617, 0.12324064, 0.35490942],
       [0.82953749, 0.09729264, 0.67008506],
       [0.25839239, 0.94053517, 0.05341007],
       [0.5243085 , 0.79357529, 0.32319951]])

In [102]:
arr[1:8, [0,1,2]]

array([[0.23796595, 0.70774173, 0.05502202],
       [0.06959043, 0.08272529, 0.76775645],
       [0.63276813, 0.22742075, 0.11446601],
       [0.45111617, 0.12324064, 0.35490942],
       [0.82953749, 0.09729264, 0.67008506],
       [0.25839239, 0.94053517, 0.05341007],
       [0.5243085 , 0.79357529, 0.32319951]])

In [103]:
a2 = arr[1:8, [0,1,2]]

In [104]:
a2

array([[0.23796595, 0.70774173, 0.05502202],
       [0.06959043, 0.08272529, 0.76775645],
       [0.63276813, 0.22742075, 0.11446601],
       [0.45111617, 0.12324064, 0.35490942],
       [0.82953749, 0.09729264, 0.67008506],
       [0.25839239, 0.94053517, 0.05341007],
       [0.5243085 , 0.79357529, 0.32319951]])

In [105]:
a2[0][0]

0.23796594977700047

In [106]:
a2[0][0] = 100 # reassigning value in dataset

In [107]:
a2

array([[1.00000000e+02, 7.07741731e-01, 5.50220190e-02],
       [6.95904344e-02, 8.27252920e-02, 7.67756452e-01],
       [6.32768127e-01, 2.27420751e-01, 1.14466011e-01],
       [4.51116173e-01, 1.23240644e-01, 3.54909421e-01],
       [8.29537487e-01, 9.72926418e-02, 6.70085062e-01],
       [2.58392391e-01, 9.40535168e-01, 5.34100719e-02],
       [5.24308500e-01, 7.93575291e-01, 3.23199512e-01]])

In [108]:
a = [[1,2],[3,4]]
b = [[2,3],[4,5]]

In [109]:
a

[[1, 2], [3, 4]]

In [110]:
b

[[2, 3], [4, 5]]

In [111]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [112]:
a

array([[1, 2],
       [3, 4]])

In [113]:
b

array([[2, 3],
       [4, 5]])

In [114]:
# try to multiply matrix a and b

In [115]:
a*b        # this is just a element wise multiplication

array([[ 2,  6],
       [12, 20]])

In [116]:
a@b     #@ symbol representing matrix multiplication
         #* symbol represent element wise multiplication

array([[10, 13],
       [22, 29]])

In [117]:
m = a@b

In [118]:
m/0

<ipython-input-118-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [2]:
import numpy as np

In [120]:
l = [1,2,3,4,5,6]

In [121]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [122]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [124]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [126]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [127]:
 np.ones(5)

array([1., 1., 1., 1., 1.])

In [128]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [130]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [131]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
5+ np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [4]:
np.empty((4,5))

array([[2.12199579e-314, 4.24399158e-314, 4.24399158e-314,
        9.88131292e-324, 6.23054972e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 2.22522597e-306,
        6.89811602e-307, 9.34602321e-307],
       [8.01089062e-307, 1.20160711e-306, 6.23055651e-307,
        1.33511018e-306, 1.69120281e-306]])

In [134]:
np.empty((5))

array([1., 1., 1., 1., 1.])

In [135]:
np.empty((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [136]:
np.empty((5,4,2))

array([[[0.79958208, 0.87757302],
        [0.51841684, 0.21308259],
        [0.94518547, 0.23796595],
        [0.70774173, 0.05502202]],

       [[0.81255234, 0.4226759 ],
        [0.06959043, 0.08272529],
        [0.76775645, 0.58234051],
        [0.87154278, 0.63276813]],

       [[0.22742075, 0.11446601],
        [0.15516758, 0.6932206 ],
        [0.45111617, 0.12324064],
        [0.35490942, 0.10205173]],

       [[0.65045803, 0.82953749],
        [0.09729264, 0.67008506],
        [0.71034379, 0.08787481],
        [0.25839239, 0.94053517]],

       [[0.05341007, 0.40768647],
        [0.18495674, 0.5243085 ],
        [0.79357529, 0.32319951],
        [0.71559149, 0.03849401]]])

In [138]:
np.linspace(2,6) # it can generates values between these two limits

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [140]:
np.linspace(2,8,6)

array([2. , 3.2, 4.4, 5.6, 6.8, 8. ])

In [141]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [142]:
np.linspace(2,8,100)

array([2.        , 2.06060606, 2.12121212, 2.18181818, 2.24242424,
       2.3030303 , 2.36363636, 2.42424242, 2.48484848, 2.54545455,
       2.60606061, 2.66666667, 2.72727273, 2.78787879, 2.84848485,
       2.90909091, 2.96969697, 3.03030303, 3.09090909, 3.15151515,
       3.21212121, 3.27272727, 3.33333333, 3.39393939, 3.45454545,
       3.51515152, 3.57575758, 3.63636364, 3.6969697 , 3.75757576,
       3.81818182, 3.87878788, 3.93939394, 4.        , 4.06060606,
       4.12121212, 4.18181818, 4.24242424, 4.3030303 , 4.36363636,
       4.42424242, 4.48484848, 4.54545455, 4.60606061, 4.66666667,
       4.72727273, 4.78787879, 4.84848485, 4.90909091, 4.96969697,
       5.03030303, 5.09090909, 5.15151515, 5.21212121, 5.27272727,
       5.33333333, 5.39393939, 5.45454545, 5.51515152, 5.57575758,
       5.63636364, 5.6969697 , 5.75757576, 5.81818182, 5.87878788,
       5.93939394, 6.        , 6.06060606, 6.12121212, 6.18181818,
       6.24242424, 6.3030303 , 6.36363636, 6.42424242, 6.48484

In [143]:
np.linspace(4,5,10)

array([4.        , 4.11111111, 4.22222222, 4.33333333, 4.44444444,
       4.55555556, 4.66666667, 4.77777778, 4.88888889, 5.        ])

In [144]:
#it generates single diamention arays only

In [145]:
np.linspace(2,8,10).reshape(2,5)    # it will convert any arrays into any kind of diamention

array([[2.        , 2.66666667, 3.33333333, 4.        , 4.66666667],
       [5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ]])

In [146]:
#it will consider upper bound or upperlimit aslo

In [147]:
np.linspace(2,8,10, endpoint = False).reshape(2,5) # it will remove upperbound

array([[2. , 2.6, 3.2, 3.8, 4.4],
       [5. , 5.6, 6.2, 6.8, 7.4]])

In [148]:
np.linspace(2,8,10,endpoint = False, retstep=True)     #it will show you a step size of data to be passed

(array([2. , 2.6, 3.2, 3.8, 4.4, 5. , 5.6, 6.2, 6.8, 7.4]), 0.6)

In [150]:
np.linspace(2,8,90,endpoint = False, retstep=True)  

(array([2.        , 2.06666667, 2.13333333, 2.2       , 2.26666667,
        2.33333333, 2.4       , 2.46666667, 2.53333333, 2.6       ,
        2.66666667, 2.73333333, 2.8       , 2.86666667, 2.93333333,
        3.        , 3.06666667, 3.13333333, 3.2       , 3.26666667,
        3.33333333, 3.4       , 3.46666667, 3.53333333, 3.6       ,
        3.66666667, 3.73333333, 3.8       , 3.86666667, 3.93333333,
        4.        , 4.06666667, 4.13333333, 4.2       , 4.26666667,
        4.33333333, 4.4       , 4.46666667, 4.53333333, 4.6       ,
        4.66666667, 4.73333333, 4.8       , 4.86666667, 4.93333333,
        5.        , 5.06666667, 5.13333333, 5.2       , 5.26666667,
        5.33333333, 5.4       , 5.46666667, 5.53333333, 5.6       ,
        5.66666667, 5.73333333, 5.8       , 5.86666667, 5.93333333,
        6.        , 6.06666667, 6.13333333, 6.2       , 6.26666667,
        6.33333333, 6.4       , 6.46666667, 6.53333333, 6.6       ,
        6.66666667, 6.73333333, 6.8       , 6.86

In [151]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [152]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [154]:
np.linspace(2,4,10) # compare it

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [159]:
a = np.arange(16)

In [160]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [161]:
a = np.arange(16).reshape(4,4)

In [162]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [163]:
a.max()  #it will give you max number or elements not a index

15

In [164]:
a.min()

0

In [165]:
a = np.arange(4,40).reshape(3,6,2)

In [166]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [167]:
a.max(axis= 1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [168]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [169]:
a = np.arange(4,40).reshape(6,6)

In [170]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [171]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [172]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [173]:
a.min(axis=0)

array([4, 5, 6, 7, 8, 9])

In [174]:
a.min(axis=1)

array([ 4, 10, 16, 22, 28, 34])

In [175]:
# axis = 0 ==consider a row
# axis = 1 ==consider as column

In [9]:
a = np.arange(4,40).reshape(6,6)

In [10]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [11]:
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [12]:
a/10

array([[0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. , 2.1],
       [2.2, 2.3, 2.4, 2.5, 2.6, 2.7],
       [2.8, 2.9, 3. , 3.1, 3.2, 3.3],
       [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]])

In [13]:
a/0

<ipython-input-13-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [14]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [15]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [16]:
pow(a,2)       

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [17]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [18]:
pow(a,5)

array([[    1024,     3125,     7776,    16807,    32768,    59049],
       [  100000,   161051,   248832,   371293,   537824,   759375],
       [ 1048576,  1419857,  1889568,  2476099,  3200000,  4084101],
       [ 5153632,  6436343,  7962624,  9765625, 11881376, 14348907],
       [17210368, 20511149, 24300000, 28629151, 33554432, 39135393],
       [45435424, 52521875, 60466176, 69343957, 79235168, 90224199]],
      dtype=int32)

In [19]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [20]:
b = np.array([2,3,3,1,2,3])

In [21]:
b

array([2, 3, 3, 1, 2, 3])

In [26]:
a + b # it is tryieng to perform operation row wise

array([[ 6,  8,  9,  8, 10, 12],
       [12, 14, 15, 14, 16, 18],
       [18, 20, 21, 20, 22, 24],
       [24, 26, 27, 26, 28, 30],
       [30, 32, 33, 32, 34, 36],
       [36, 38, 39, 38, 40, 42]])

In [27]:
#try to perform columnwise operation

In [28]:
b = b.T   # b is one diaention array it is not possible to rotate a one diametinal array

In [29]:
a + b

array([[ 6,  8,  9,  8, 10, 12],
       [12, 14, 15, 14, 16, 18],
       [18, 20, 21, 20, 22, 24],
       [24, 26, 27, 26, 28, 30],
       [30, 32, 33, 32, 34, 36],
       [36, 38, 39, 38, 40, 42]])

In [199]:
b

array([2, 3, 3, 1, 2, 3])

In [206]:
b = b.reshape(1,-1) #b = b.reshape(-1,1) ,b = b.reshape(6,1)      *this is also possible

In [201]:
b

array([[2, 3, 3, 1, 2, 3]])

In [204]:
b.T

array([[2],
       [3],
       [3],
       [1],
       [2],
       [3]])

In [205]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [203]:
a + b   # it is possible column wise operation

array([[ 6,  8,  9,  8, 10, 12],
       [12, 14, 15, 14, 16, 18],
       [18, 20, 21, 20, 22, 24],
       [24, 26, 27, 26, 28, 30],
       [30, 32, 33, 32, 34, 36],
       [36, 38, 39, 38, 40, 42]])

In [207]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [208]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [209]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [210]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [ ]:
#CONCEPT BEHIND DEEP COPY AND SOLLOW COPY

In [30]:
x = np.array([1,2,3])

In [31]:
y = x         # sollow copy if i change any thing it will affect on other one

In [32]:
y

array([1, 2, 3])

In [33]:
z = np.copy(x)       # deep copy

In [34]:
z

array([1, 2, 3])

In [35]:
x[0] = 100

In [36]:
y

array([100,   2,   3])

In [37]:
z

array([1, 2, 3])

In [38]:
id(x)

2205462732016

In [39]:
id(y)

2205462732016

In [40]:
id(z)

2205458259760

In [41]:
#id concept

In [42]:
x

array([100,   2,   3])

In [43]:
y

array([100,   2,   3])

In [46]:
id(x[0])

2205462728112

In [47]:
id(y[0])   # it is not going to same

2205462728336

In [48]:
id(x[1])

2205462728368

In [49]:
id(y[1])

2205462727728

In [50]:
id(z[1])

2205462728624

In [51]:
  x = np.array([1,2,3])

In [52]:
y = x

In [53]:
id(x)

2205462888688

In [54]:
id(y)      # these are same bcoz of same memori bit location but inside their index is not same

2205462888688

In [55]:
id(x[0])

2205462934416

In [56]:
id(y[0])

2205462934576

In [57]:
s = np.array([567,345])

In [58]:
df =  s

In [59]:
id(s)

2205462889936

In [60]:
id(df)

2205462889936

In [61]:
id(s[0])

2205462935344

In [62]:
id(df[0])

2205462935120

In [63]:
id(s[1])

2205462935600

In [64]:
id(df[1])

2205462935824

In [65]:
id(s[1]) == id(df[1])

True

In [266]:
xt = np.array([34,67,89])

In [267]:
id(xt[0]) == id(s[0])

True

In [268]:
c = "sudh"

In [270]:
id(c) == id(s[0])

False